on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:

name: Deploy smartmeter-exporter to Raspberry Pi

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Deploy
      env:
          SOURCEINFO: "\"{\\\"owner\\\":\\\"u-one\\\", \\\"repository\\\":\\\"go-el-controller\\\", \\\"path\\\": \\\"deployments\\\"}\""
          BROUTEID: ${{ secrets.BROUTEID }}
          BROUTEPW: ${{ secrets.BROUTEPW }}
      run: |
        aws ssm send-command --document-name "AWS-RunRemoteScript" \
            --instance-ids "mi-03255646b7984d8e2" \
            --parameters "{\"sourceType\":[\"GitHub\"],\"sourceInfo\":[$SOURCEINFO],\"commandLine\":[\"deploy-smartmeter-exporter.sh $BROUTEID $BROUTEPW\"]}"
